### ISSUE TITLE
host website on github pages

### ISSUE THREAD

**Issue by milahu** [peggyjs/peggy#2]
hey phpnode / codemix - thanks for [fork and rollback](https://github.com/pegjs/pegjs/issues/639#issuecomment-731571802) : )

could we host the website on github pages?
https://pegjs.org/online looks like a static html-javascript page, so gh-pages should work

.. either by creating a branch gh-pages, or a separate repository, like pegjs-pages

hope the license says yeah

**Comment by phpnode** [comment]
sounds good to me, @mdamien has a fork of the editor with nice inline errors, https://github.com/pegjs/pegjs/issues/658 we should try and incorporate that if possible. I haven't checked the licensing situation for the site yet tho.

**Comment by milahu** [comment]
just found the build scripts in https://github.com/pegjs/pegjs/tree/master/website
so they have the same license = MIT

**Comment by hildjj** [comment]
Status: I've checked all the files into `/docs`, turned on Pages hosting for that, and am in the process of getting DNS fixed up for `peggyjs.org`, which will take a day or two for all of the DNS propagation.

**Comment by hildjj** [comment]
Note that there's still work to do to disentangle the webpack bits; the code that some parts of the site are using is still peg.js branded.

**Comment by hildjj** [comment]
Fixed, see https://peggyjs.org/ which serves up https://github.com/peggyjs/peggy/tree/main/docs

**Comment by hildjj** [comment]
whoops, I had it on www.peggyjs.org, but I'm fixing that up.  Leaving this open until everything settles back down.

**Comment by hildjj** [comment]
Looks like that's holding now.  www.peggyjs.org 301's to peggyjs.org.  Details for anyone who finds this later:

From dreamhost:

```
www CNAME peggyjs.github.io
@ ALIAS peggyjs.github.io
@ NS ns1.dreamhost.com.
@ NS ns2.dreamhost.com.
@ NS ns3.dreamhost.com.
```

GitHub pages set to serve '/docs' from the `main` branch, and then https://github.com/peggyjs/peggy/blob/main/docs/CNAME contains:

```
peggyjs.org
```

Note that GitHub Pages will allow `/docs/foo.html` to be requested as `https://peggyjs.org/foo`, with no `.html` extension, which is good, because there are likely still some links in the page without an extension.
