### ISSUE TITLE
Migration challanges

### ISSUE THREAD

**Issue by physikerwelt** [peggyjs/peggy#244]
In https://github.com/wikimedia/mediawiki-services-texvcjs/commit/80b18ad2db045c856a9b79a64178e702d91d09fc we migrated from peg.js to peggy. During this migration I belive to have found two differences:

1)  It seems that peggy has a toString function in the Error class whereas peg.js did not have this function.
2) In the error description the expected regexp pattern contains additional commata. However, this would match also the comma in most interpretations of regexp groups.

Is this correct?

If yes,
-> Is 2) a bug, that could be fixed?
-> Should 1) be added to the readme?

Upstream ticket for reference https://phabricator.wikimedia.org/T308842

**Comment by Mingun** [comment]
Comma in char class expected error text is a bug that was fixed (but not yet released) in #197. @hildjj, the silence in the project dragged on somewhat. I think it is worth making the release in its current form, since the new features added from the latest release are already enough production-ready. If you are too busy to devote enough time to the project, I can help. True, I don't have much time either, but two people are still better than one.

**Comment by physikerwelt** [comment]
I tested the `"peggy": "peggyjs/peggy#1.3"` branch, but it did not work for me
```
> mathoid-texvcjs@0.3.11 test
> node -e 'require("./lib/build-parser")' && npm run lint && mocha

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'source-map-generator'
Require stack:
- /Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/compiler/passes/generate-js.js
- /Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/compiler/index.js
- /Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/peg.js
- /Users/physikerwelt/git/mediawiki/texvcjs/lib/build-parser.js
- /Users/physikerwelt/git/mediawiki/texvcjs/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/compiler/passes/generate-js.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/compiler/passes/generate-js.js',
    '/Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/compiler/index.js',
    '/Users/physikerwelt/git/mediawiki/texvcjs/node_modules/peggy/lib/peg.js',
    '/Users/physikerwelt/git/mediawiki/texvcjs/lib/build-parser.js',
    '/Users/physikerwelt/git/mediawiki/texvcjs/[eval]'
  ]
}
```
not sure if that is helpful feedback

**Comment by physikerwelt** [comment]
It works on `"peggy": "peggyjs/peggy#bd3798dd6f13ab48913aa55933ec50fba346312f"` but not with `"peggy": "peggyjs/peggy#8bc052c41bee1d78a43f76a80c2bb9ee4373f4ff"`(with the last one I get the same error as above)

**Comment by physikerwelt** [comment]
@Mingun thank you. With the following patch, I don't have migration issues:

https://github.com/physikerwelt/texvcjs/commit/dad05f88599423bd87616900d8434febd4298f56

**Comment by hildjj** [comment]
I'm moving this project back toward the top of my priority list.  Let's discuss what goes in the 1.3 relese on #221.

**Comment by physikerwelt** [comment]
> I tested the `"peggy": "peggyjs/peggy#1.3"` branch, but it did not work for me

this might be #223 ?

**Comment by hildjj** [comment]
Yes, that backtrace looks like 223.  Try adding `source-map-generator` to your project to confirm.

**Comment by physikerwelt** [comment]
> Yes, that backtrace looks like 223. Try adding `source-map-generator` to your project to confirm.

works, cf. https://github.com/wikimedia/mediawiki-services-texvcjs/commit/6cb221b7b31cee80ce3c14e121686222b93a7c04#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R37-R38

**Comment by physikerwelt** [comment]
The only thing in this ticket that is not already answered elsewhere remains if there is a better way to get backward compatibility to the old peg.js error handling as my approach here 

https://github.com/physikerwelt/texvcjs/commit/dad05f88599423bd87616900d8434febd4298f56#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R51-R53

**Comment by physikerwelt** [comment]
In #116 @hildjj wrote

> This may break a few people who are relying on error formatting. I want to make sure we've discussed that adequately. Do we need to take a major version number bump for this?

I guess this is exactly what did happen here. I guess tests fail since errors and plain objects are not the same in terms of `===`

**Comment by Mingun** [comment]
For history: we found, that breakage was related to how the @physikerwelt code uses the Peggy API and how the assertion library performs checks:
- the whole `parser.SyntaxError` object was stored
- it is asserted by the assertion library (using [deprecated assert.deepEqual](https://nodejs.org/api/assert.html#assertdeepequalactual-expected-message) method)
- after [changing its prototype chain](https://github.com/peggyjs/peggy/commit/e52dc26730973fa4278b0d60c96f31ef2f357190) the assertion failed, probably because it was strict about types (probably assertion requires that sample object was an `Error` instance too)
- when assertion failed, diff is forming, for the `Error` descendants its probably calls `toString()`, and for the sample object -- `JSON.stringify`. That is why the diff as shown in the [output](https://integration.wikimedia.org/ci/job/generic-node12-docker/1666/console) is formed, which could not reflect the actual reason of assertion failing

Solution was found: store not all but only a significant part of the `SyntaxError` object. The other possible solution probably would be to change the assertion to explicitly assert the `Error` type or use non-deprecated method.

As a result, I think, that problem was investigated and can be closed.

**Comment by hildjj** [comment]
@physikerwelt please re-open or start a new ticket if this continues to be an issue.  In particular, I'm very open to adding more properties to the `SyntaxError` object so that nobody has to parse the `toString` text.

**Comment by physikerwelt** [comment]
Thank you. I think we found a good solution for my case now. Is there an estimate for the 1.3 release date?

**Comment by hildjj** [comment]
> Is there an estimate for the 1.3 release date?

Probably a week or two.  Follow the progress on #221.  Also, it's going to be a 2.0 release, since we're going to drop support for Node v10.
