### ISSUE TITLE
Peggy vs PEG.js

### ISSUE THREAD

**Issue by jcubic** [peggyjs/peggy#249]
What are the differences between Peggy and PEG.js? I wanted to look at PEG.js Codemirror grammar file and maybe migrate it to Peggy. Since it's hard to edit Peggy grammar with PEG.js syntax highlighting in Codemirror.

**Comment by Mingun** [comment]
The full list o changes is https://github.com/peggyjs/peggy/compare/Renaissance...main.

The count of functional changes in grammar not so big and listed in https://github.com/peggyjs/peggy/blob/main/CHANGELOG.md, namely:

- #73: Added global initializer blocks, which contain code that is only run once
  when the grammar is loaded, rather than once every time the parser runs.
  Global initializers are surrounded by `{{` and `}}`, and must come before
  the per-parser initializer, which is surrounded by `{` and `}`.
- #89: Back-ported value plucking with `@` from pegjs head.  If your rule has a simple action that returns one or more of the values matched by the rule, you can instead mark those expressions with `@` and not need an action.  This works inside of parens as well.

**Comment by jcubic** [comment]
Thanks, I think that there is a lot more to even PEG.js that is not implemented in Codemirror grammar that is very simple. [My language](https://gaiman.js.org/) is all messed up in the editor.

**Comment by Mingun** [comment]
If you mean this artifact then it seems that `$` symbols confuse a highlighter:
![$ artifact](https://user-images.githubusercontent.com/450131/170748525-20af6401-ce06-4831-b408-d380bb451dc3.png)

**Comment by jcubic** [comment]
Thanks, will investigate, maybe issue is with JavaScript mode.

**Comment by jcubic** [comment]
Is this syntax different in Peggy:

```
extra_commands = _ method:adapter_asterisk_strings SPACE expr:command_argument SPACE args:(
    ("," _ expression)+ / '' {
        if (expr.type !== 'SpreadElement') {
            error('Command ' + method+ ' require at least two arguments`);
        }
    }) _ {
    if (args) {
        args = args.map(x => x[2]);
    }
    return  {
        "type": "AwaitExpression",
        "argument": gaiman_call(map_extra_method(method), expr, ...(args || []))
    };
}
```

It's not highlighted properly unless I delete the first JS code.

**Comment by hildjj** [comment]
Aren't you missing at least one `)` in there?  It'd be easier to see if you split `args` into a separate rule.

**Comment by MarcelBolten** [comment]
Is it the backtick
~~~
' require at least two arguments`
~~~
vs the single quote
~~~
' require at least two arguments'
~~~

**Comment by hildjj** [comment]
I think this was solved.
