### ISSUE TITLE
Inverstigate changes in generated grammar

### ISSUE THREAD

**Issue by physikerwelt** [peggyjs/peggy#259]
From https://github.com/peggyjs/peggy/issues/221#issuecomment-1140313930

After upgrading from bd3798dd6f13ab48913aa55933ec50fba346312f to the npm 2.0.0 version the generated grammar I
> realized that there are a few duplicated rules. [In my case](https://gerrit.wikimedia.org/r/c/mediawiki/services/texvcjs/+/793836/2..3/lib/parser.js#343), there were 151 functions before and now there are 203. Sometimes the exact same functions follow each other. Eventually, all tests still pass so this might only be a cosmetic issue, but it would feel good to understand this change.

If anyone knows why the grammar looks different this would be of great help.

**Comment by Mingun** [comment]
Yes, that is consequence of the source map support. Now each source code in the grammar mapped to its own function in order to provide correct mapping.

Maybe that can be improved if generation of source map is not requested, and even when source map is generated at the cost of worsening mappings (some generated code will refer to the wrong location in the source `.peggy` file)

**Comment by physikerwelt** [comment]
That makes perfect sense. An argument to generate the source map, if it is already paid;-) While testing I did not realize a performance decay, and running a stress test also does not show decay in performance.
