### ISSUE TITLE
V8 crashes when trying to parse a list

### ISSUE THREAD

**Issue by tornikeshavishvili** [peggyjs/peggy#357]
Hello

V8 crashes when trying to use following grammar:

```
test 'test'
 = ss:'aa'|1..8,((_+'.'_+)/(_+','_+))|{
 return ss
}

_ "whitespace"
  = [ \t\n\r]* {
    return ''
  }
```
my node: v18.7.0
chrome: Version 110.0.5481.177 (Official Build) (64-bit)

I suspect that crash happens upon successful mach.

![image](https://user-images.githubusercontent.com/4466636/221383996-5929f29e-be3f-43ec-8026-3dbdb5dcba52.png)

@Mingun

**Comment by Mingun** [comment]
The reason in that `_+` creates an infinity parse loop, because `_` is always matched (because it could match empty input). You should change the `_` definition:
```diff
 _ "whitespace"
-  = [ \t\n\r]* {
+  = [ \t\n\r] {
     return ''
   }
```

It seems an oversight from my side. We should run `check(node.delimiter)` somewhere here:
https://github.com/peggyjs/peggy/blob/00855f6757dd2483fe03cd82f2e1e1b245b44fdb/lib/compiler/passes/report-infinite-repetition.js#L28-L53

**Comment by hildjj** [comment]
Can we get this into a 3.0.1 release in the next day or two, or should I go ahead without it?

**Comment by tornikeshavishvili** [comment]
I want have look as soon as possible on provided code, but . . . i have difficulties to understand what is written and why :(((

**Comment by hildjj** [comment]
@Mingun I'd like to get this fixed before the release, if you have the time.

**Comment by hildjj** [comment]
I've got it.  When I tried it the first time, I put the check in the wrong place.  Adding tests now.
