### ISSUE TITLE
How to use a generated parse in TypeScript program

### ISSUE THREAD

**Issue by evil-shrike** [peggyjs/peggy#571]
Hi.
I generated a parser using the online generator, downloaded it as CommonJS. But my project is in TypeScript, so I need a type declaration for the generated file.
I'm running this:
```
npx -p typescript tsc ./parser.js  --declaration --allowJs --emitDeclarationOnly
```
where parser.js is the generated parser.
I'm getting an error:
parser.js:1:1 - error TS9005: Declaration emit for this file requires using private name 'peg$SyntaxError'. An explicit type annotation may unblock declaration emit.

1 module.exports = // @generated by Peggy 4.1.1.

Any ideas how to fix?

**Comment by hildjj** [comment]
- Install peggy locally, with something like `npm install --save-dev peggy`
- Use `--format es` if you are in an ES6 project, otherwise, use `--format commonjs`
- Use `--dts` to output a .d.ts file next to the .js file
- Set the output of peggy to be your typescript dist directory
- From the typescript file where you want to use your parser, use `import {parse} from '../dist/parser.js'` for example.

**Comment by hildjj** [comment]
Please re-open this issue if it turns out the suggested approach doesn't work.
