### ISSUE TITLE
Readme doesn't include "es" format

### ISSUE THREAD

**Issue by GreenImp** [peggyjs/peggy#71]
The description of the `format` option, in the readme file is:

> `--format` — format of the generated parser: `amd`, `commonjs`, `globals`, `umd` (default: `commonjs`)

But Peggy includes an `es` option as well.

It's worth noting that the [CLI documentation](https://peggyjs.org/documentation#generating-a-parser-command-line) does have the `es` type listed:

> Format of the generated parser: `amd`, `commonjs`, `globals`, `umd`, `es` (default: `commonjs`).

But, the dependencies section for the [JS API](https://peggyjs.org/documentation#generating-a-parser-javascript-api) says:
> valid only when format is set to "amd", "commonjs", or "umd"

Where it should include es" in the list.

I could try and get a PR in to fix these things, but I'm not sure when I'll get the time to do so.

**Comment by hildjj** [comment]
Waiting on monorepo branch

**Comment by StoneCypher** [comment]
Requesting the use of the token `es2015` to be in keeping with ts, rollup, webpack, rome, etc

Hildjj suggested maintaining `es` as a synonym, seems fine

**Comment by hildjj** [comment]
Rollup seems to use `es`?  https://rollupjs.org/guide/en/#outputformat

**Comment by hildjj** [comment]
Webpack seems to use `module`: https://webpack.js.org/configuration/output/#librarytarget-module

**Comment by hildjj** [comment]
I can't figure out what rome is using; they're not doing bundling yet, right?

**Comment by StoneCypher** [comment]
... huh.  i wonder if `es2015` is a synonym in rollup now

i guess i'm just wrong about webpack

it's `es2015` in typescript because there are subtle differences already for es2018, because it can collide conceptually with the old es4x module notation, and because there's good reason to believe either es9 or es10 will include types, which will change the export spec.  i believe typescript is making the right choice.

rome i don't use.  it describes itself as a bundler?  `Rome is a linter, compiler, bundler, and more for JavaScript, TypeScript, JSON, HTML, Markdown, and CSS.\nRome is designed to replace Babel, ESLint, webpack, Prettier, Jest, and others.`  the reason I expected them to use `es2015` is they're written in Typescript and claim complete Typescript compatability, but I was just wrong about `rollup`, and I can't find it either, so now I'm receding from thinking I know the answer

**Comment by StoneCypher** [comment]
anyway, if rollup, webpack, and typescript disagree, then i think you can pretty much do what you want

please don't call it prolog

**Comment by StoneCypher** [comment]
seems fine.  i was just appealing for community norms, and it seems there isn't one
