### ISSUE TITLE
Move to rollup

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy#83]
switch out browserify to rollup.

**Comment by StoneCypher** [comment]
In order to do this, it would be best for me to switch things from `commonjs` to `import/export` internally.  

Just making sure you're okay with my doing that, at large scale, before I proceed

**Comment by hildjj** [comment]
I'm fine with that, particularly since node 10 goes EOL in ~10 days.

**Comment by hildjj** [comment]
note: I know that doesn't affect our users, but it's a conceptual breakpoint for the industry.

**Comment by StoneCypher** [comment]
Rollup can happily still dump commonjs, and I advocate that it still should, at the end of the day

In my heart of hearts, one day you will embrace typescript, and then this will even still work in older versions of node, lol

**Comment by StoneCypher** [comment]
As you see fit.

**Comment by hildjj** [comment]
Is it possible to generate the VERSION string from package.json at rollup time?  If you're in node, not using the rollup build, the code could then just read from package.json at runtime lazily.

This would tremendously simplify the release process to the point where it could be put in CI much more easily.

**Comment by StoneCypher** [comment]
> Is it possible to generate the VERSION string from package.json at rollup time?

It's pretty easy to do it in the step right before.

You *can* do it with something like `rollup-plugin-replace`, but I personally don't like to do that

The thing I tend to do as a preference instead is to have [a trivial piece of legitimate source](https://github.com/StoneCypher/jssm/blob/main/src/ts/version.ts) that just has the version in it, then in a directory for "build js," ideally kept extremely minimal since it's not-app, [to just delete and recreate that source](https://github.com/StoneCypher/jssm/blob/main/src/buildjs/makever.js) as a build product in what amounts to a prior miniature build pass.

It's more like a makefile, in one sense: there's two build products, one of which is used by the other, and thus generated first

What I'm recommending is "let's do it at build time in general, rather than more specifically at rollup time"

To me this strategy seems roughly equivalent, but my opinion is that keeping it just before rollup, instead of as part of it, is relatively simpler in the long run.  I am somewhat against the practice of trying to stuff things into the build system; my opinion is that it's one of the long term dangerous and problematic parts of almost every JS/TS project, and that keeping things outside of it is typically desirable, for roughly the same reasons as you would with a standard library, a microkernel, a secure boundary, etc; my assertion is that a risk area is best bounded and reduced

One nice thing about the strategy is that, in addition to generating it at build time, since it's in source, you can also now use it directly in the app quite easily.  For something like `peg` this isn't that big a deal (although if we start adding features, we'll probably end up wanting to let a grammar specify its minimum peg implementation, and now suddenly it does matter,) but by example, it's kind of nice to see a version number tick up on a site I use.

Happy to do it either way as you prefer; have done both in the past.

**Comment by StoneCypher** [comment]
Sure if you like
